/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package java11;
import jaco.mp3.player.MP3Player;
import java.io.File;

/**
 *
 * @author shreya
 */
public class bpraak extends javax.swing.JFrame {

    /**
     * Creates new form bpraak
     */
    public bpraak() {
        initComponents();
    }

public static final String Playb="‪C:\\Users\\shreya\\Downloads\\Mann Bharrya-(Mr-Jatt.com).mp3"; 
MP3Player playb=new MP3Player(new File(Playb));
public static final String Playb1="‪‪C:\\Users\\shreya\\Downloads\\Teri Mitti-(Mr-Jatt.com).mp3"; 
MP3Player playb1=new MP3Player(new File(Playb1));
public static final String Playb2="‪‪C:\\Users\\shreya\\Downloads\\O_Saki_Saki_Ft_Tulsi_Kumar_1.mp3"; 
MP3Player playb2=new MP3Player(new File(Playb2));
public static final String Playb3="‪‪‪C:\\Users\\shreya\\Downloads\\Maana Dil  Good Newwz -(Mr-Jatt.com).mp3"; 
MP3Player playb3=new MP3Player(new File(Playb3));
public static final String Playb4="‪‪‪‪C:\\Users\\shreya\\Downloads\\Dance_Like_1.mp3"; 
MP3Player playb4=new MP3Player(new File(Playb4));

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ply = new javax.swing.JButton();
        ply1 = new javax.swing.JButton();
        ply2 = new javax.swing.JButton();
        ply3 = new javax.swing.JButton();
        ply4 = new javax.swing.JButton();
        ply5 = new javax.swing.JButton();
        ply6 = new javax.swing.JButton();
        ply7 = new javax.swing.JButton();
        ply8 = new javax.swing.JButton();
        ply9 = new javax.swing.JButton();
        ply10 = new javax.swing.JButton();
        ply11 = new javax.swing.JButton();
        ply12 = new javax.swing.JButton();
        ply13 = new javax.swing.JButton();
        ply14 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 0), 3));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java11/b praak img.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 593, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Maana Dil");
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 321, 319, 26));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Oo Saki Saki");
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 369, 319, 26));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Teri Mitti");
        jLabel4.setOpaque(true);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 409, 319, 26));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Mann Bharrya");
        jLabel5.setOpaque(true);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 453, 319, 26));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Dance Like");
        jLabel6.setOpaque(true);
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 498, 320, 26));

        ply.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java11/play.jpg"))); // NOI18N
        ply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plyActionPerformed(evt);
            }
        });
        jPanel1.add(ply, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 360, 30, 30));

        ply1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java11/pppbuttons.jpg"))); // NOI18N
        ply1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ply1ActionPerformed(evt);
            }
        });
        jPanel1.add(ply1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 320, 30, 30));

        ply2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java11/stop.jpg.png"))); // NOI18N
        ply2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ply2ActionPerformed(evt);
            }
        });
        jPanel1.add(ply2, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 320, 30, 30));

        ply3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java11/play.jpg"))); // NOI18N
        ply3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ply3ActionPerformed(evt);
            }
        });
        jPanel1.add(ply3, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 320, 30, 30));

        ply4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java11/pppbuttons.jpg"))); // NOI18N
        ply4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ply4ActionPerformed(evt);
            }
        });
        jPanel1.add(ply4, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 360, 30, 30));

        ply5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java11/stop.jpg.png"))); // NOI18N
        ply5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ply5ActionPerformed(evt);
            }
        });
        jPanel1.add(ply5, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 360, 30, 30));

        ply6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java11/play.jpg"))); // NOI18N
        ply6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ply6ActionPerformed(evt);
            }
        });
        jPanel1.add(ply6, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 400, 30, 30));

        ply7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java11/pppbuttons.jpg"))); // NOI18N
        ply7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ply7ActionPerformed(evt);
            }
        });
        jPanel1.add(ply7, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 400, 30, 30));

        ply8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java11/stop.jpg.png"))); // NOI18N
        ply8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ply8ActionPerformed(evt);
            }
        });
        jPanel1.add(ply8, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 440, 30, 30));

        ply9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java11/play.jpg"))); // NOI18N
        ply9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ply9ActionPerformed(evt);
            }
        });
        jPanel1.add(ply9, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 480, 30, 30));

        ply10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java11/pppbuttons.jpg"))); // NOI18N
        ply10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ply10ActionPerformed(evt);
            }
        });
        jPanel1.add(ply10, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 440, 30, 30));

        ply11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java11/stop.jpg.png"))); // NOI18N
        ply11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ply11ActionPerformed(evt);
            }
        });
        jPanel1.add(ply11, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 400, 30, 30));

        ply12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java11/play.jpg"))); // NOI18N
        ply12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ply12ActionPerformed(evt);
            }
        });
        jPanel1.add(ply12, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 440, 30, 30));

        ply13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java11/pppbuttons.jpg"))); // NOI18N
        ply13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ply13ActionPerformed(evt);
            }
        });
        jPanel1.add(ply13, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 480, 30, 30));

        ply14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java11/stop.jpg.png"))); // NOI18N
        ply14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ply14ActionPerformed(evt);
            }
        });
        jPanel1.add(ply14, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 480, 30, 30));

        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java11/backbutton.jpg"))); // NOI18N
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 530, 50, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Groove On B Praak's Latest Songs ! ");
        jLabel7.setOpaque(true);
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 548, -1, 26));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java11/ariii.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        jLabel8.setOpaque(true);
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1280, 610));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1282, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void plyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plyActionPerformed
playb2.play();        // TODO add your handling code here:
    }//GEN-LAST:event_plyActionPerformed

    private void ply6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ply6ActionPerformed
playb1.play();        // TODO add your handling code here:
    }//GEN-LAST:event_ply6ActionPerformed

    private void ply9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ply9ActionPerformed
playb4.play();      // TODO add your handling code here:
    }//GEN-LAST:event_ply9ActionPerformed

    private void ply11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ply11ActionPerformed
playb1.stop();        // TODO add your handling code here:
    }//GEN-LAST:event_ply11ActionPerformed

    private void ply12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ply12ActionPerformed
playb.play();        // TODO add your handling code here:
    }//GEN-LAST:event_ply12ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        new homepages().setVisible(true); 
this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void ply1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ply1ActionPerformed
playb3.pause();        // TODO add your handling code here:
    }//GEN-LAST:event_ply1ActionPerformed

    private void ply2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ply2ActionPerformed
playb3.stop();        // TODO add your handling code here:
    }//GEN-LAST:event_ply2ActionPerformed

    private void ply4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ply4ActionPerformed
playb2.pause();        // TODO add your handling code here:
    }//GEN-LAST:event_ply4ActionPerformed

    private void ply5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ply5ActionPerformed
playb2.stop();        // TODO add your handling code here:
    }//GEN-LAST:event_ply5ActionPerformed

    private void ply7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ply7ActionPerformed
playb1.play();        // TODO add your handling code here:
    }//GEN-LAST:event_ply7ActionPerformed

    private void ply8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ply8ActionPerformed
playb.stop();        // TODO add your handling code here:
    }//GEN-LAST:event_ply8ActionPerformed

    private void ply10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ply10ActionPerformed
playb.pause();        // TODO add your handling code here:
    }//GEN-LAST:event_ply10ActionPerformed

    private void ply13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ply13ActionPerformed
playb4.pause();        // TODO add your handling code here:
    }//GEN-LAST:event_ply13ActionPerformed

    private void ply14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ply14ActionPerformed
playb4.stop();        // TODO add your handling code here:
    }//GEN-LAST:event_ply14ActionPerformed

    private void ply3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ply3ActionPerformed

    }//GEN-LAST:event_ply3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bpraak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bpraak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bpraak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bpraak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bpraak().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton16;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton ply;
    private javax.swing.JButton ply1;
    private javax.swing.JButton ply10;
    private javax.swing.JButton ply11;
    private javax.swing.JButton ply12;
    private javax.swing.JButton ply13;
    private javax.swing.JButton ply14;
    private javax.swing.JButton ply2;
    private javax.swing.JButton ply3;
    private javax.swing.JButton ply4;
    private javax.swing.JButton ply5;
    private javax.swing.JButton ply6;
    private javax.swing.JButton ply7;
    private javax.swing.JButton ply8;
    private javax.swing.JButton ply9;
    // End of variables declaration//GEN-END:variables
}
